#!/usr/bin/env python3
"""Generate input data for effchango: test image, sine table, and tone phase increments."""

import argparse
import math
import struct
import os

# Musical note frequencies (Hz) - pentatonic-ish spread across octaves
# Matches the spirit of the original PhotoChango tones
TONE_FREQS = [
    # Row 0 (bottom) - low octave
    130.81, 146.83, 164.81, 196.00, 220.00, 246.94, 261.63, 293.66, 329.63, 349.23,
    # Row 1
    196.00, 220.00, 246.94, 261.63, 293.66, 329.63, 349.23, 392.00, 440.00, 493.88,
    # Row 2
    261.63, 293.66, 329.63, 349.23, 392.00, 440.00, 493.88, 523.25, 587.33, 659.26,
    # Row 3
    329.63, 349.23, 392.00, 440.00, 493.88, 523.25, 587.33, 659.26, 698.46, 783.99,
    # Row 4
    392.00, 440.00, 493.88, 523.25, 587.33, 659.26, 698.46, 783.99, 880.00, 987.77,
    # Row 5
    523.25, 587.33, 659.26, 698.46, 783.99, 880.00, 987.77, 1046.50, 1174.66, 1318.51,
    # Row 6
    659.26, 698.46, 783.99, 880.00, 987.77, 1046.50, 1174.66, 1318.51, 1396.91, 1567.98,
    # Row 7
    783.99, 880.00, 987.77, 1046.50, 1174.66, 1318.51, 1396.91, 1567.98, 1760.00, 1975.53,
    # Row 8
    987.77, 1046.50, 1174.66, 1318.51, 1396.91, 1567.98, 1760.00, 1975.53, 2093.00, 2349.32,
    # Row 9 (top) - high octave
    1174.66, 1318.51, 1396.91, 1567.98, 1760.00, 1975.53, 2093.00, 2349.32, 2637.02, 2793.83,
]

SAMPLE_RATE = 8000
SINE_TABLE_SIZE = 256
NUM_GRID_X = 10
NUM_GRID_Y = 10
NUM_TONES = NUM_GRID_X * NUM_GRID_Y
IMG_WIDTH = 100
IMG_HEIGHT = 100
NUM_AUDIO_SAMPLES = 16000  # 2 seconds at 8000 Hz


def generate_sine_table():
    """Generate a 256-entry Q15 sine lookup table."""
    table = []
    for i in range(SINE_TABLE_SIZE):
        val = math.sin(2.0 * math.pi * i / SINE_TABLE_SIZE)
        q15 = int(round(val * 32767))
        q15 = max(-32767, min(32767, q15))
        table.append(q15)
    return table


def compute_phase_increments():
    """Compute phase increments for each tone frequency.

    Phase accumulator is uint32_t, wraps at 2^32.
    Table index = (phase >> 24) & 0xFF for 256-entry table.
    phase_inc = freq * 2^32 / sample_rate
    """
    incs = []
    for freq in TONE_FREQS:
        inc = int(round(freq * (2**32) / SAMPLE_RATE))
        incs.append(inc & 0xFFFFFFFF)
    return incs


def generate_test_image():
    """Generate a synthetic 100x100 grayscale test image.

    Creates a pattern with varying brightness regions to produce
    interesting audio output - diagonal gradient with some circular features.
    """
    pixels = []
    cx, cy = IMG_WIDTH // 2, IMG_HEIGHT // 2
    for y in range(IMG_HEIGHT):
        for x in range(IMG_WIDTH):
            # Base: diagonal gradient
            base = int((x + y) * 255 / (IMG_WIDTH + IMG_HEIGHT - 2))

            # Add circular bright spot
            dx = x - cx
            dy = y - cy
            dist = math.sqrt(dx * dx + dy * dy)
            circle = max(0, int(200 * (1.0 - dist / (IMG_WIDTH * 0.4))))

            # Add some grid-like variation
            grid = 50 if ((x // 20) + (y // 20)) % 2 == 0 else 0

            val = min(255, base + circle + grid)
            pixels.append(val)
    return pixels


def write_array(f, arr, typename, per_line=10):
    """Write a C array literal."""
    for i, v in enumerate(arr):
        if i != 0:
            f.write(", ")
        if i % per_line == 0 and i != 0:
            f.write("\n    ")
        f.write(str(v))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output", required=True, help="Output .h file")
    parser.add_argument("--num-samples", type=int, default=NUM_AUDIO_SAMPLES)
    args = parser.parse_args()

    sine_table = generate_sine_table()
    phase_incs = compute_phase_increments()
    test_image = generate_test_image()

    with open(args.output, "w") as f:
        f.write("/* Auto-generated by gen_data.py - do not edit */\n")
        f.write("#include <stdint.h>\n\n")

        # Image dimensions
        f.write(f"#define IMG_WIDTH {IMG_WIDTH}\n")
        f.write(f"#define IMG_HEIGHT {IMG_HEIGHT}\n")
        f.write(f"#define NUM_GRID_X {NUM_GRID_X}\n")
        f.write(f"#define NUM_GRID_Y {NUM_GRID_Y}\n")
        f.write(f"#define NUM_TONES {NUM_TONES}\n")
        f.write(f"#define SINE_TABLE_SIZE {SINE_TABLE_SIZE}\n")
        f.write(f"#define SAMPLE_RATE {SAMPLE_RATE}\n")
        f.write(f"#define NUM_AUDIO_SAMPLES {args.num_samples}\n\n")

        # Test image (grayscale, 0-255)
        f.write(f"#ifdef DEFINE_CHANGO_DATA\n\n")

        f.write(f"const uint8_t test_image[{IMG_WIDTH * IMG_HEIGHT}] = {{\n    ")
        write_array(f, test_image, "uint8_t", per_line=20)
        f.write("\n};\n\n")

        # Sine lookup table (Q15)
        f.write(f"const int16_t sine_table[{SINE_TABLE_SIZE}] = {{\n    ")
        write_array(f, sine_table, "int16_t", per_line=10)
        f.write("\n};\n\n")

        # Phase increments per tone
        f.write(f"const uint32_t phase_incs[{NUM_TONES}] = {{\n    ")
        write_array(f, phase_incs, "uint32_t", per_line=5)
        f.write("\n};\n\n")

        f.write("#endif /* DEFINE_CHANGO_DATA */\n")

    print(f"Generated {args.output}")
    print(f"  Image: {IMG_WIDTH}x{IMG_HEIGHT} grayscale")
    print(f"  Tones: {NUM_TONES} ({NUM_GRID_X}x{NUM_GRID_Y} grid)")
    print(f"  Sine table: {SINE_TABLE_SIZE} entries (Q15)")
    print(f"  Audio: {args.num_samples} samples at {SAMPLE_RATE} Hz "
          f"({args.num_samples / SAMPLE_RATE:.1f}s)")


if __name__ == "__main__":
    main()
